[workspace]
members = ["modules/api"]

[workspace.dependencies]
anyhow = {version = "1.0.66", features = ["backtrace"] }
axum = "0.6.1"
serde = { version = "1.0", features = ["derive"] }
testcontainers = "0.14.0"
tokio = { version = "1.23.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
