version: "3.9"

services:
  sqs:
    image: softwaremill/elasticmq
    port:
      - 9324:9324
      - 9325:9325
    volumes:
      - ./conf/test/elasticmq.conf:/opt/elasticmq.conf
      - ./tmp/elasticmq:/data

  database:
    image: postgres:14.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 15432:5432
    volumes:
      - ./tmp/database/postgres:/var/lib/postgresql/data
      - ./tmp/database/logs:/var/log
    restart: always
