version: "3.9"

services:
  database:
    image: postgres:14.1
    environment:
      POSTGRES_DB: local_opxs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 15432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:
