version: "3.9"

services:
  db:
    image: postgres:14.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 15432:5432
    volumes:
      - ./tmp/db/postgres:/var/lib/postgresql/data
      - ./tmp/db/logs:/var/log
    restart: always
