[package]
name = "opxs-api"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
migration = { path = "../migration" }
aws-config = { workspace = true }
aws-sdk-secretsmanager = { workspace = true }
lambda-web = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
testcontainers = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
sqlx = { workspace = true }
tower-http = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
config = { workspace = true }
ring = { workspace = true }
hex = { workspace = true }
clap = { workspace = true }

[dev-dependencies]
testcontainers = { workspace = true }
