name: build-and-deploy-dev

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout submodule
        uses: actions/checkout@v2
        with:
          repository: omnius-labs/core-rs
          path: refs/core-rs
          ssh-key: ${{ secrets.PRIVATE_REPO_SSH_KEY }}
          persist-credentials: true
      - name: Update submodule
        run: git submodule update --init

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: Build bin
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.build
          push: false
          tags: opxs-api-build-image
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
      - name: Copy bin
        run: |
          docker run --name opxs-api-builder -d opxs-api-build-image
          docker cp opxs-api-builder:/app ./bin
          docker rm opxs-api-builder

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: aws-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push image to Amazon ECR (opxs-api)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: ${{ steps.aws-ecr.outputs.registry }}/opxs-api-lambda:latest
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Update lambda
        run: |
          aws lambda update-function-code --function-name opxs-api --image-uri ${{ steps.aws-ecr.outputs.registry }}/opxs-api-lambda:latest
