name: build-and-deploy-dev

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: aws-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and Push image to Amazon ECR
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: ${{ steps.aws-ecr.outputs.registry }}/opxs-api-lambda:latest
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Update lambda
        run: |
          aws lambda update-function-code --function-name opxs-api --image-uri ${{ steps.aws-ecr.outputs.registry }}/opxs-api-lambda:latest
