name: build-and-deploy-dev

on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout submodule
        uses: actions/checkout@v4
        with:
          repository: omnius-labs/core-rs
          path: refs/core-rs
          ssh-key: ${{ secrets.PRIVATE_REPO_SSH_KEY }}
          persist-credentials: true
      - name: Update submodule
        run: git submodule update --init

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: Build bin
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.build
          push: false
          tags: opxs-api-build-image
          provenance: false
          cache-from: type=s3,region=us-east-1,bucket=opxs.v1.dev.docker-build-cache,name=opxs-api-builder
          cache-to: type=s3,region=us-east-1,bucket=opxs.v1.dev.docker-build-cache,name=opxs-api-builder,mode=max
          load: true
      - name: Copy bin
        run: |
          docker run --name opxs-api-builder -d opxs-api-build-image
          docker cp opxs-api-builder:/app ./bin
          docker stop opxs-api-builder
          docker rm opxs-api-builder

      - name: Login to Amazon ECR
        id: aws-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push image to Amazon ECR (opxs-api)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: ${{ steps.aws-ecr.outputs.registry }}/opxs-api:latest
          provenance: false
          cache-from: type=s3,region=us-east-1,bucket=opxs.v1.dev.docker-build-cache,name=opxs-api
          cache-to: type=s3,region=us-east-1,bucket=opxs.v1.dev.docker-build-cache,name=opxs-api,mode=max
      - name: Update ECS
        run: |
          aws ecs update-service --cluster opxs-api-cluster --service opxs-api --force-new-deployment

      - name: Build and Push image to Amazon ECR (opxs-batch-email-send)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.batch-email-send
          push: true
          tags: ${{ steps.aws-ecr.outputs.registry }}/opxs-batch-email-send:latest
          provenance: false
          cache-from: type=s3,region=us-east-1,bucket=opxs.v1.dev.docker-build-cache,name=opxs-batch-email-send
          cache-to: type=s3,region=us-east-1,bucket=opxs.v1.dev.docker-build-cache,name=opxs-batch-email-send,mode=max
      - name: Update Lambda
        run: |
          aws lambda update-function-code --function-name opxs-batch-email-send --image-uri ${{ steps.aws-ecr.outputs.registry }}/opxs-batch-email-send:latest
