name: test

on:
  push:
    branches:
      - "**"
    paths:
      - "**"
      - "!/docs/**"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Setup rust toolchain
        id: rust_toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.66.1
      - name: Setup cargo make
        uses: davidB/rust-cargo-make@v1
        with:
          version: "latest"
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
          key: ${{ runner.os }}-cargo-${{ steps.rust_toolchain.outputs.rustc_hash }}-${{ hashFiles('Cargo.lock') }}
      - name: Test
        run: cargo make test
