name: update

on:
  pull_request:
    types: [opened, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'dependabot'
    steps:
      - name: update rust version
        id: update_rust_version
        run: python .github/workflows/update.py
      - name: create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update rust
          delete-branch: true
          title: "Update Rust ${{ steps.update_rust_version.outputs.rust_version }}"
