name: update-rust-toolchain

on:
  pull_request:
    paths:
      - "rust-toolchain"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout submodule
        uses: actions/checkout@v4
        with:
          repository: omnius-labs/core-rs
          path: refs/core-rs
          ssh-key: ${{ secrets.PRIVATE_REPO_SSH_KEY }}
          persist-credentials: true
      - name: Update submodule
        run: git submodule update --init

      - name: update rust version
        id: update_rust_version
        run: python .github/workflows/update-rust-toolchain.py
      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_WORKFLOW_UPDATE }}
          base: ${{ github.head_ref }}
          commit-message: "update: rust version"
          delete-branch: true
          title: "[Update] Rust toolchain version ${{ steps.update_rust_version.outputs.rust_version }}"
          branch: features/update-rust-version
